GET http://localhost:3030/getAuthors

####

POST http://localhost:3030/createAuthor
Content-Type: application/json

{
    "firstName": "Giovanni",
    "lastName": "Verdi",
    "email": "miaemail@gmail.com",
    "birthday": "1968-09-12",
    "avatar": ""
}

####
GET http://localhost:3030/getAuthor/65f3521d8e77449cf7586720

####
PATCH http://localhost:3030/updateAuthor/65f3521d8e77449cf7586720
Content-Type: application/json

{
    "lastName": "new lastname"
}

####
DELETE http://localhost:3030/deleteAuthor/65f3521d8e77449cf7586720