GET http://localhost:3030/getAuthors

####

POST http://localhost:3030/createAuthor
Content-Type: application/json

{
    "firstName": "Mario",
    "lastName": "Rossi",
    "email": "miaemail@gmail.com",
    "birthday": "1990-03-28",
    "avatar": ""
}

####
GET http://localhost:3030/getAuthor/65f3521d8e77449cf7586720